export const drinkNames = {
  // CAFÉ & CACAO
  "Phin Đen Đá": "Iced Black Coffee",
  "Phin Sữa Đá": "Iced Milk Coffee",
  "Bạc Xỉu Đá": "Iced White Coffee",
  "Cacao Sữa Đá": "Iced Cocoa Milk",
  "Cacao Sữa Bạc Hà": "Iced Peppermint Cocoa Milk",
  "Cacao Kem Cheese": "Cocoa with Cheese Cream",

  // SMOOTHIES
  "Smoothies Đào": "Peach Smoothie",
  "Smoothies Việt Quất": "Blueberry Smoothie",
  "Smoothies Hi-berry Mộc Nhiên": "Moc Nhien Hi-berry Smoothie",

  // SINH TỐ - ĐÁ XAY
  "Sinh Tố Bơ": "Avocado Smoothie",
  "Sinh Tố Dâu": "Strawberry Smoothie",
  "Coffee Choco": "Coffee Chocolate Smoothie",
  "Cacao Đá Xay": "Blended Cocoa Ice",
  "Matcha Đá Xay": "Blended Matcha Ice",
  "Cookies Choco Mint": "Cookies Chocolate Mint Smoothie",

  // HIBICUS - TRÀ TRÁI CÂY
  "Lipton Đá": "Iced Lipton Tea",
  "Trà Hoa Cúc": "Chrysanthemum Tea",
  "Trà Mận": "Plum Tea",
  "Trà Ổi Hồng": "Pink Guava Tea",
  "Trà Tắc Mật Ong": "Honey Kumquat Tea",
  "Trà Dâu": "Strawberry Tea",
  "Trà Đào": "Peach Tea",
  "Trà Oolong Vải": "Oolong Lychee Tea",
  "Trà Hoa Cúc Mật Ong": "Honey Chrysanthemum Tea",
  "Trà Đào Cam Sả": "Peach Orange Lemongrass Tea",
  "Trà Vải Hoa Hồng": "Lychee Rose Tea",
  "Trà Cam Ổi Dâu Tây": "Orange Guava Strawberry Tea",
  "Trà Ổi Hồng Chanh Dây": "Pink Guava Passion Fruit Tea",
  "Trà Hibicus Vải": "Hibiscus Lychee Tea",
  "Trà Hibicus Đào": "Hibiscus Peach Tea",
  "Trà Trái Cây Mộc Nhiên": "Moc Nhien Fruit Tea",

  // TRÀ SỮA
  "Trà Sữa Truyền Thống": "Traditional Milk Tea",
  "Trà Oolong Sữa": "Oolong Milk Tea",
  "Trà Sữa Matcha": "Matcha Milk Tea",
  "Trà Sữa Chocolate": "Chocolate Milk Tea",

  // THỨC UỐNG NÓNG
  "Lipton Nóng": "Hot Lipton Tea",
  "Trà Hoa Cúc Nóng": "Hot Chrysanthemum Tea",
  "Ca Cao Sữa Nóng": "Hot Cocoa Milk",

  // YOGURT - NƯỚC ÉP
  "Yogurt Đá": "Iced Yogurt",
  "Yogurt Dâu": "Strawberry Yogurt",
  "Yogurt Việt Quất": "Blueberry Yogurt",
  "Yogurt Trái Cây Mộc Nhiên": "Moc Nhien Fruit Yogurt",
  "Nước Ép Thơm": "Pineapple Juice",
  "Nước Ép Ổi Hồng": "Pink Guava Juice",
  "Nước Ép Dưa Hấu": "Watermelon Juice",
  "Nước Ép Táo": "Apple Juice",
  "Nước Ép Cam Thơm": "Orange Pineapple Juice",
  "Nước Ép Táo Thơm": "Apple Pineapple Juice",

  // TRÀ MACHIATO
  "Trà Vải Machiato": "Lychee Tea Macchiato",
  "Trà Dâu Machiato": "Strawberry Tea Macchiato",
  "Hồng Trà Machiato": "Black Tea Macchiato",
  "Trà Sen Vàng Machiato": "Golden Lotus Tea Macchiato",

  // BÁNH NGỌT
  "Panna Cotta": "Panna Cotta",
  "Cheese Chanh Dây": "Passion Fruit Cheesecake",
  "Cheese Phúc Bồn Tử": "Blueberry Cheesecake",
  "Tiramisu": "Tiramisu",

  // MÓN THÊM
  "Kem Phô Mai Machiato": "Cheese Cream Macchiato Topping",
  "Hạt Ngọc Trai": "Pearl",
  "Hạt Caramel": "Caramel Pearl",
  "Pudding Trứng": "Egg Pudding",
  "Khúc Bạch": "Almond Jelly",
  "Sen": "Lotus Seeds",
  "Ổi": "Guava",
  "Dưa Hấu": "Watermelon",
  "Đào": "Peach",
  "Vải": "Lychee",
  "Dâu": "Strawberry",
  "Thạch Dừa": "Coconut Jelly",
  "Thạch Dâu": "Strawberry Jelly",
};

export const menuItems = {
  cafeAndCacao: [
    "Phin Đen Đá",
    "Phin Sữa Đá",
    "Bạc Xỉu Đá",
    "Cacao Sữa Đá",
    "Cacao Sữa Bạc Hà",
    "Cacao Kem Cheese",
  ],
  smoothies: [
    "Smoothies Đào",
    "Smoothies Việt Quất",
    "Smoothies Hi-berry Mộc Nhiên",
  ],
  sinhToDaXay: [
    "Sinh Tố Bơ",
    "Sinh Tố Dâu",
    "Coffee Choco",
    "Cacao Đá Xay",
    "Matcha Đá Xay",
    "Cookies Choco Mint",
  ],
  hibicusTraTraiCay: [
    "Lipton Đá",
    "Trà Hoa Cúc",
    "Trà Mận",
    "Trà Ổi Hồng",
    "Trà Tắc Mật Ong",
    "Trà Dâu",
    "Trà Đào",
    "Trà Oolong Vải",
    "Trà Hoa Cúc Mật Ong",
    "Trà Đào Cam Sả",
    "Trà Vải Hoa Hồng",
    "Trà Cam Ổi Dâu Tây",
    "Trà Ổi Hồng Chanh Dây",
    "Trà Hibicus Vải",
    "Trà Hibicus Đào",
    "Trà Trái Cây Mộc Nhiên",
  ],
  traSua: [
    "Trà Sữa Truyền Thống",
    "Trà Oolong Sữa",
    "Trà Sữa Matcha",
    "Trà Sữa Chocolate",
  ],
  thucUongNong: [
    "Lipton Nóng",
    "Trà Hoa Cúc Nóng",
    "Ca Cao Sữa Nóng",
  ],
  yogurtNuocEp: [
    "Yogurt Đá",
    "Yogurt Dâu",
    "Yogurt Việt Quất",
    "Yogurt Trái Cây Mộc Nhiên",
    "Nước Ép Thơm",
    "Nước Ép Ổi Hồng",
    "Nước Ép Dưa Hấu",
    "Nước Ép Táo",
    "Nước Ép Cam Thơm",
    "Nước Ép Táo Thơm",
  ],
  traMatchiato: [
    "Trà Vải Machiato",
    "Trà Dâu Machiato",
    "Hồng Trà Machiato",
    "Trà Sen Vàng Machiato",
  ],
  banhNgot: [
    "Panna Cotta",
    "Cheese Chanh Dây",
    "Cheese Phúc Bồn Tử",
    "Tiramisu",
  ],
  monThem: [
    "Kem Phô Mai Machiato",
    "Hạt Ngọc Trai",
    "Hạt Caramel",
    "Pudding Trứng",
    "Khúc Bạch",
    "Sen",
    "Ổi",
    "Dưa Hấu",
    "Đào",
    "Vải",
    "Dâu",
    "Thạch Dừa",
    "Thạch Dâu",
  ],
};